openapi: '3.0.2'
info:
  title: Documentation de l'API DESIGNIMAGE
  version: '1.0'
servers:
    - url: https://localhost:3000/api
paths:
  /designImage/:
    get:
      summary: Récupérer toutes les images par ID
      description: Retourne les informations de l'utilisateur correspondant à l'ID spécifié
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/designimage'
    post:
      summary: Ajouter un nouvel utilisateur
      description: Ajoute un nouveeau designimage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUdesignimage'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/designimage'
        '400':
          description: Requête invalide
        '401':
          description: Non authentifié
  /designImage/{designImage_id}:
    get:
      summary: Récupérer un utilisateur par ID
      description: Retourne les informations de l'utilisateur correspondant à l'ID spécifié
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: L'identifiant de l'utilisateur à récupérer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/designimage'
        '404':
          description: designimage introuvable
    put:
      summary: Mettre à jour un designimage par ID
      description: Met à jour le designimage correspondant à l'ID spécifié
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: L'identifiant de ledesignimage à mettre à jour
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/designimageUpdate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/designimage'
        '400':
          description: Requête invalide
        '404':
          description: Utilisateur introuvable
    delete:
      summary: Supprimer un designimage par ID
      description: Supprime le designimage correspondant à l'ID spécifié
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: L'identifiant du designimage à supprimer
      responses:
        '204':
          description: OK
        '404':
          description: designimage introuvable

components:
  schemas:
    designimage:
      type: object
      properties:
        designImage_id:
          type: integer
          description: Id de designImage
          format: uuid
        design_id:
          type: integer
          description: clé étrangère
          format: uuid
        image:
          type: string
          format: file
          description: image designImage
        thumbnail:
          type: string 
          format: file
          description: image designImage

        
    designimageUpdate:
      type: object
      properties:
        designImage_id:
          type: integer
          description: Id de designImage 
          format: uuid
        design_id:
          type: integer
          description: clé étrangère
          format: uuid
        image:
          type: string
          format: file
          description: image designImage mis à jour
        thumbnail:
          type: string 
          format: file
          description: image designImage mis à jour
    
    NewUdesignimage:
      type: object
      properties:
        designImage_id:
          type: integer
          description: Id de designImage
          format: uuid
        design_id:
          type: integer
          description: clé étrangère
          format: uuid
        image:
          type: string
          format: file
          description: nouvel image designImage 
        thumbnail:
          type: string 
          format: file
          description: nouvel image de fond designImage 
      required:
        - designImage_id
        - design_id
        - image
        - thumbnail


